- id: tv_off
  alias: TV off
  trigger:
  - platform: state
    entity_id: media_player.samsung_tv_remote
    from: 'on'
    to: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: light.kitchen  # tv light actually

- id: tv_on
  alias: TV on
  trigger:
  - platform: state
    entity_id: media_player.samsung_tv_remote
    from: 'off'
    to: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: light.kitchen

- alias: Notify when add item
  id: notify_when_add_item_to_shopping_list
  trigger:
  - entity_id: sensor.shopping_list
    platform: state
  action:
  - service: script.notify_on_telegram
    data:
      title: 'Lista de compras atualizada!'
      message: '{{ states.sensor.shopping_list.state }}'

- alias: Notify when precipitation > 15%
  id: notify_when_it_will_rain
  trigger:
  - platform: template
    value_template: "{% if states.sensor.dark_sky_precip_probability.state | float >= 15.0 %} true {% endif %}"
  action:
  - service: script.notify_on_telegram
    data:
      title: 'Melhor pegar o guarda-chuvas...️'
      message: '{{ states.sensor.dark_sky_precip_probability.state }}% de probabilidade de chuva.'

- alias: Notify when tablet needs to be charged (30%)
  id: notify_when_tablet_needs_to_be_charged_30
  trigger:
  - platform: template
    value_template: "{% if states.sensor.wallpanel_battery_level.state | float <= 30.0 %} true {% endif %}"
  action:
  - service: script.notify_on_telegram
    data:
      title: 'Hora de recarregar o tablet.'
      message: '{{ states.sensor.wallpanel_battery_level.state }}%'

- alias: Notify when tablet needs to be charged (15%)
  id: notify_when_tablet_needs_to_be_charged_15
  trigger:
  - platform: template
    value_template: "{% if states.sensor.wallpanel_battery_level.state | float <= 15.0 %} true {% endif %}"
  action:
  - service: script.notify_on_telegram
    data:
      title: 'A bateria do tablet está acabando!'
      message: '{{ states.sensor.wallpanel_battery_level.state }}%'
