- alias: "Media player paused/stopped"
  trigger:
      - platform: state
        entity_id: media_player.samsung_tv_remote
        from: 'playing'
        to: 'idle'
  condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_normal

- alias: "Media player playing"
  trigger:
      - platform: state
        entity_id: media_player.samsung_tv_remote
        to: 'playing'
        from: 'idle'
  condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_dim

- alias: "Notify when add item"
  trigger:
    - platform: state
      entity_id: sensor.shopping_list
  action:
    service: notify.telegram
    data_template:
      message: >
        Nossa lista de compras foi atualizada!
        
        {{states.sensor.shopping_list.state}}