- alias: Media player paused/stopped
  id: media_player_paused_stoped
  trigger:
  - platform: state
    entity_id: media_player.samsung_tv_remote
    from: 'on'
    to: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: group.living_room

- alias: Media player playing
  id: media_player_playing
  trigger:
  - platform: state
    entity_id: media_player.samsung_tv_remote
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: group.living_room

- alias: Notify when add item
  id: notify_when_add_item_to_shopping_list
  trigger:
  - entity_id: sensor.shopping_list
    platform: state
  action:
  - entity_id: script.notify_on_telegram
    service: script.reload
