homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

automation: !include automations.yaml
script: !include scripts.yaml

group: !include groups.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml

frontend:

config:

http:
    api_password: !secret api_password

updater:
   include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

tts:
  - platform: google

cast:

media_player:
  - platform: samsungtv
    host: !secret samsung_tv_ip
    port: !secret samsung_tv_port
    mac: !secret samsung_tv_mac

shopping_list:

emulated_hue:
    host_ip: !secret host
    entities:
        light.kitchen:
          name: "Kitchen light"
        light.kitchen_2:
          name: "TV light"

cloud:
    alexa:
        filter:
          include_entities:
            - light.kitchen # tv
            - light.kitchen_2 # dinner table
        entity_config:
          light.kitchen:
            name: TV light
            description: The light over the tv
            display_categories: LIGHT
          light.kitchen_2:
            name: Kitchen light
            description: The Kitchen light
            display_categories: LIGHT

panel_iframe:
  configurator:
    title: 'Configurator'
    url: !secret configurator
    icon: mdi:wrench
  terminal:
    title: Terminal
    icon: mdi:console
    url: !secret terminal_address

weblink:
  entities:
    - name: Router
      url: !secret router_url
      icon: mdi:router-wireless

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_key

ecovacs:
  username: !secret ecovacs_username
  password: !secret ecovacs_password
  country: de
  continent: eu

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_ana
      - !secret telegram_mateus

notify:
  - name: telegram_ana
    platform: telegram
    chat_id: !secret telegram_ana
  - name: telegram_mateus
    platform: telegram
    chat_id: !secret telegram_mateus

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

weather:
  - platform: yweather
    name: Weather

# logger:
#   logs:
#     homeassistant.components.ecovacs: debug
#     homeassistant.components.vacuum.ecovacs: debug
#     sucks: debug
#     sensors.shopping_list: debug
