homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

automation: !include automations.yaml
script: !include scripts.yaml

group: !include groups.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml

frontend:
    themes:
        midnight: !include theme_midnight.yaml

config:

http:

updater:
   include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

media_player:
  - platform: samsungtv
    host: !secret samsung_tv_ip
    port: !secret samsung_tv_port
    mac: !secret samsung_tv_mac
    timeout: 5

shopping_list:

emulated_hue:
    host_ip: !secret host
    entities:
        light.kitchen:
          name: "Kitchen light"
        light.kitchen_2:
          name: "TV light"

panel_iframe:
  logviewer:
    title: Logs
    icon: mdi:file-document-box-outline
    url: !secret logviewer_address

panel_custom:
  - name: hassio-main
    sidebar_title: Configurator
    sidebar_icon: hass:settings
    js_url: /api/hassio/app/entrypoint.js
    url_path: configurator
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

weblink:
  entities:
    - name: Router
      url: !secret router_url
      icon: mdi:router-wireless
    - name: Dashboard
      url: !secret lovelace
      icon: mdi:desktop-mac-dashboard

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_key

ecovacs:
  username: !secret ecovacs_username
  password: !secret ecovacs_password
  country: de
  continent: eu

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_ana
      - !secret telegram_mateus

notify:
  - name: telegram_ana
    platform: telegram
    chat_id: !secret telegram_ana
  - name: telegram_mateus
    platform: telegram
    chat_id: !secret telegram_mateus

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

mqtt:
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

logger:
  logs:
    media_player.samsung_tv_remote: debug
#     homeassistant.components.ecovacs: debug
#     homeassistant.components.vacuum.ecovacs: debug
#     sucks: debug
#     sensors.shopping_list: debug

fastdotcom:

system_health:
