- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - precip_probability
    - temperature
    - precip_intensity

- platform: worldclock
  time_zone: America/Fortaleza

- platform: worldclock
  time_zone: Europe/Berlin

- platform: alpha_vantage
  api_key: !secret alpha_vantage_api_key
  foreign_exchange:
  - from: EUR
    to: BRL
    name: Euro/Real

- platform: time_date
  display_options:
    - 'time_date'

- platform: mqtt
  state_topic: "homeassistant/mywallpanel/sensor/battery"
  name: "WallPanel Battery Level"
  unit_of_measurement: "%"
  value_template: '{{ value_json.value }}'
