- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - precip_probability
    - temperature

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: deutsche_bahn
  from: Samariterstr. (U), Berlin
  to: Bernauer Str. (U), Berlin
  
# - platform: deutsche_bahn
#   from: Samariterstr. (U), Berlin
#   to: Oranienburger Str. (S), Berlin

- platform: fastdotcom

- platform: worldclock
  time_zone: America/Fortaleza

- platform: worldclock
  time_zone: Europe/Berlin

- platform: command_line
  name: shopping_list
  command: "python3 /config/shopping_list.py"

- platform: alpha_vantage
  api_key: !secret alpha_vantage_api_key
  foreign_exchange:
  - from: EUR
    to: BRL
    name: Euro/Real
  - from: BTC
    to: BRL
    name: Bitcoin/Real