title: Home
excluded_entities:
  - weblink.router
views:
  - title: Home
    icon: mdi:home-assistant
    cards:
      - type: entities
        title: 'Lights control'
        entities:
          - light.kitchen
          - light.kitchen_2
        card:
          type: glance 
          title: Living Room Lights
      - type: glance
        title: World Clock
        entities:
          - entity: sensor.worldclock_sensor_2
            name: Brasil
          - entity: sensor.worldclock_sensor
            name: Berlin
      - type: entities
        title: Weather
        entities:
          - entity: sun.sun
          - entity: sensor.dark_sky_temperature
          - entity: sensor.dark_sky_precip_probability
      - type: media-control
        entity: media_player.samsung_tv_remote
      - type: conditional
        conditions:
            - entity: media_player.samsung_tv_remote
              state: "on"
        card:
          type: entities
          entity: media_player.cantincast
    #   - type: weather-forecast
    #     entity: weather.dark_sky
      - type: iframe
        url: http://192.168.0.8:8123/shopping-list
        aspect_ratio: 100%


