title: Home
excluded_entities:
  - weblink.router
views:
  - title: Home
    icon: mdi:home-assistant
    cards:
      - type: entities
        title: 'Lights control'
        entities:
          - light.kitchen
          - light.kitchen_2
        card:
          type: glance 
          title: Living Room Lights
      - type: vertical-stack
        cards:
          - type: glance
            title: World Clock
            entities:
              - entity: sensor.worldclock_sensor
                name: Brasil
          - type: glance
            title: Currencies
            entities:
              - entity: sensor.euroreal
                name: Reais
              - entity: sensor.bitcoinreal
                name: Reais
              - entity: sensor.bitcoineuro
                name: Euros
      - type: glance
        title: Home to Work
        entities:
          - entity: sensor.samariterstr_u_berlin_to_bernauer_str_u_berlin
            name: Thermondo
      - type: weather-forecast
        entity: weather.weather
      - type: vertical-stack
        cards:
          - type: iframe
            url: !secret shopping_list
            aspect_ratio: 100%
          - type: entities
            entities:
              - sensor.date__time